language: node_js
node_js:
  - 18
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
before_install: cd testing
install:
  - npm ci
script:
  - npm run e2e