sonar.projectKey=yashUcr773_learn_angular
sonar.organization=yashucr773
sonar.sources=src,server
sonar.host.url=https://sonarcloud.io
sonar.javascript.lcov.reportPaths=./coverage/reports/report-lcov/lcov.info